### PR TITLE
fix(filters): angular filter detroying

### PR DESCRIPTION
**Pull request by ljacques**
an angular filter component is never destroy when the hide and show a
column or a reorder.

### CODE REVIEW

**Comment by ghiscoding** [comment]
I see this is an Example Filter, I rarely check them.
Thanks for the contribution but looking at the internal filters and the `destroy` is never called internally by a Filter, instead it's called by the `FilterService` [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/filter.service.ts#L108). That seems to be the only place, is the method called by the Service in the Custom Filter? It should be

**Comment by ljacques** [comment]
yes the method is called but it only destroys the last component created by 
`### const componentOuput = this.angularUtilService.createAngularComponentAppendToDom(DnlSelectFilterComponent, $headerElm);`

when you hide or reorder a column the method init is call and then a new componentOuput is created without destroying the first one.

to highlight this operation i put a console.log in the ngOnDestroy of the dynamic angular component.

**Comment by ljacques** [comment]
yes i saw the "Filter combined with sort makes rows disappear" issue.
but in don't know if it's the same reason.
No problem if you want to remove this PR. 
I keep this small modification on my side because I play a lot with the display of columns ^^
and without that I see performance declines

**Comment by ghiscoding** [comment]
Yeah technically it's a Custom Filter sample, you can use what is best on your side. But that would be different for all the internal Filter, I mean when you hide a column with an Internal Filter (e.g. Select Filter), it will do the same as the Custom Filter, at least technically it should. Do you have a problem with only Custom Filter?

**Comment by ljacques** [comment]
yes it's only with custom filter 👍

**Comment by ghiscoding** [comment]
Hmm that is strange, I quickly looked at the Custom Filter sample provided and compared with internal Filters, they look quite similar. Have you tried this [Example](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) to see if it does the same? The 2nd column uses that Custom Filter and Custom Editor

**Comment by ljacques** [comment]
i'll take a look ;)

**Pull request closed without merging**
