### PR TITLE
feat: interactive angular component api

### LINKED ISSUE #1294: Attach Angular Component in AsyncPostRender and keep it running
### Clear and concise description of the problem

Currently the approach shown in https://ghiscoding.github.io/Angular-Slickgrid/#/angular-components is merely rendering the dynamic Angular Component by waiting for one cycle and than picking up it's dom value and copying it over the cells innerHtml.

This is fine for one of renderings but is not enough for "interactive" components. As soon as your component is supposed to have Databindings and Events still working, this approach is too limiting.

### Suggested solution

What I'd propose instead is:

* provide an alternative angularUtilService.createAngularComponent (e.g. createInteractiveAngularComponent) so we dont introduce a breaking change
* the new method is: (see // INFO !!! for changes)

```typescript
createInteractiveAngularComponent<C>(component: Type<C>, targetElement?: Element, data?: any, createCompOptions?: CreateComponentOption): AngularComponentOutput {
    // Create a component reference from the component
    const componentRef = this.vcr.createComponent(component, createCompOptions);

    // Get DOM element from component
    let domElem: HTMLElement | null = null;
    const viewRef = (componentRef.hostView as EmbeddedViewRef<any>);

    // INFO !!! <------------ no longer wait for one cycle

    // get DOM element from the new dynamic Component, make sure this is read after any data and detectChanges()
    if (viewRef && Array.isArray(viewRef.rootNodes) && viewRef.rootNodes[0]) {
      domElem = viewRef.rootNodes[0] as HTMLElement;

      // when user provides the DOM element target, we will move the dynamic component into that target (aka portal-ing it)
      if (targetElement && domElem) {
        // INFO !!! <------------  replace with the nativeElement instead of just cutting out the body
        targetElement.replaceChildren(componentRef.location.nativeElement);
      }
    }

    return { componentRef, domElement: domElem as HTMLElement };
  }
```
* let the user handle the component destruction or be super-intelligent about how to automate it

---

I would create an PR introducing this new method, update the existing example to show an "interactive" component and add the tests. But I wanted to check back first with you @ghiscoding whether you think this is a useful general feature or we should keep developing this on ourselves.

### Alternative

_No response_

### Additional context

To give some context about our use case.

We have a generic base grid implementation which abstracts away the communication with the backend and server-side paging/sorting ...

It's planned to support multiple grids, tables, spreadsheets and whatsoever. Now there is a set of premade CellComponents which we'd like to re-use.

Additionally we want to be able to declaratively modify the formatter, editor etc. of an individual column:

```html
<grid-slickgrid-container [gridId]="id" [providedFilterData]="filter$ | async">

    <button *gridCustomFormatter="'ResourceName'; let item;" mat-icon type="button" (click)="sayMyName(item.ResourceName)">{{ item?.ResourceName ?? "..." }}</button>
</grid-slickgrid-container>
```

so in this example the Dev can specify that the ResourceName column should render the button as custom formatter, and this than works with every grid type we have, be it Slickgrid a simple NG-Datatable or Material Table.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by zewa666**
Adds an API to create interactive angular components, meaning not destroying them after a single render

fixes #1294

### CODE REVIEW

**Comment by zewa666** [comment]
So I've had issues running the jest unit tests and needed to comment this line in jest-pretest.ts
```
(global as any).navigator = { userAgent: 'node.js' };
```

I didn't check this in as I wasnt sure whether its just me.

**Comment by ghiscoding** [comment]
> So I've had issues running the jest unit tests and needed to comment this line in jest-pretest.ts
> 
> ```
> (global as any).navigator = { userAgent: 'node.js' };
> ```
> 
> I didn't check this in as I wasnt sure whether its just me.

Yeah that should be fine, I think I had to set the `navigator` agent for Excel download or something similar and it's been moved to Slickgrid-Universal for a while now, so it should be fine to remove it from here. Your PR looks good.

On my side I still have a lot of work left to do for the sub-menus that I'm adding and I found DOM leaks in all menus, so I'll have to fix that too. It's probably going to take a few more days, the weekend at the earliest or next week. 

Thanks for all your contributions :)

**Comment by ghiscoding** [comment]
Thanks I should be good, but if you are curious and want to take a look. This Slickgrid-Universal [PR 1141](https://github.com/ghiscoding/slickgrid-universal/pull/1141) that I merged couple days ago is 1/3 of the work. I still have to do other Menus plugins. The leak I found is about events, when closing the sub-menus I was removing the elements from the DOM but I forgot to remove the event listeners, technically speaking they will be removed when the user destroys the entire grid but I think it would still be better to remove the listeners when I destroy any of these sub-menus. Anyway, it's a work in progress which requires a few more days :)

**Comment by ghiscoding** [comment]
@zewa666 this is now available in [v6.40](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v6.4.0) release, it took me longer than I expected but it's happening so often haha. Thanks again for the contribution :)

**Comment by zewa666** [comment]
great work from yours as always. looking forward to trying out the new sub menus feature

**Pull request merged**
