### PR TITLE
fix(odata): no single quote escape required for IN operator for non-string column

### PR DESCRIPTION
**Pull request by whtan98**
See #340

### CODE REVIEW

**Comment by ghiscoding** [comment]
Thanks for the PR, would it be possible to add a [unit test](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts) for this new condition?

**Comment by ghiscoding** [comment]
Thanks for the PR, would it be possible to add a [unit test](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts) for this new condition?

**Comment by whtan98** [comment]
> Thanks for the PR, would it be possible to add a [unit test](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/__tests__/grid-odata.service.spec.ts) for this new condition?

Yes, if you don't mind that it may take longer, as this is my 1st JEST unit test

**Comment by whtan98** [comment]
Unit test done.

**Comment by ghiscoding** [comment]
Awesome thanks a lot, it's all green now 😄

**Pull request merged**
