### PR TITLE
New custom pagination component

### PR DESCRIPTION
**Pull request by sabeurch**
Dear Ghislan, 
As promised, this is the custom pagination component that is separated from the AngularSlickgridComponent.
Filtering and Sorting are done on server side.
No Promises are used.
Request url is appended this way:
`currentPage=2&selectedSort=5|true|&selectedFilter=All|All|All|All|All|JOD|All|All|All|All|All|All|`
This means, we are requesting for page nbr 2, making a sort over column nbr 5, ASC=true and filtering the content of the 6th column by value JOD.
It can be written the way developer wants it.

### CODE REVIEW

**Comment by ghiscoding** [comment]
wow this is a nice PR, there's a lot of nice things in there :)
Just curious what does SWT stands for, all I could find is related to Eclipse, is that it? 
Would it be possible to put the full SWT meaning in your demo component?

Thanks for this, I will review it soon.

**Comment by sabeurch** [comment]
Cool, it stands for Simple WidgeTs, been used locally in our projects.
To make the example correctly working, I have no idea on how to refer to the url: 
`testurl:string = '/getData.do?';` in file "swt-common-grid-test.component.ts"
`**Maybe we create several .json chunks ?** `, Or simulating data creation in the client side ?
As I told, the pagination/filtering/sorting business is fully implemented in DB side, so I cannot distribute.

**Comment by ghiscoding** [comment]
That is ok if there is no data, if you look at my [GraphQL example](https://ghiscoding.github.io/Angular-Slickgrid/#/gridgraphql), I wrote on the top that there are `no data showing` and instead I just show the GraphQL query that will be produced in that example page. If you could do that too, that would be great :)

**Comment by sabeurch** [comment]
That's fine, I'll update the sources.
Thanks.

**Comment by ghiscoding** [comment]
Let me know when you're done with the update and I'll review at that time. No rush though :)

**Comment by sabeurch** [comment]
Sources are updated.

**Comment by ghiscoding** [comment]
Thanks for the contribution, 
I will review your entire code before merging by the end of the week.

 I already took the code you made for the page number input and added to my Pagination component. It was on my TODO list, but low priority, however since you've done the missing piece, It was easy enough to copy+paste your code and it all works. Got to love Open Source. Thank you!

By the way, I added the Bootstrap class `form-control` and set certain CSS properties:
```css
height: 26px;
width: 34px;
padding: 2px;
display: inline-block;
}
``` 
and now I have the same feeling as any Bootstrap input but much smaller, see below :)

pagenumber

**Comment by sabeurch** [comment]
Yes open source is based essentially on "share or it will die". I am happy to contribute.
Thank you for the css class. I didn't spend enough time on styling as I am relatively new on Bootstrap and Angular :(

**Comment by ghiscoding** [comment]
@sabeurch 
I just pushed a new [version 0.12.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v0.12.0) that brings [Grid State & Grid Presets](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Grid-State-&-Preset) functionality, however there are a lot changes in the Backend Services. If you want to support that on your side too, you should definitely look at the PR #17 (sorry about the fact that this PR include much more than just this feature). 

What the Grid State & Preset will allow us to do is save the states of the grid in Local Storage and re-use them as a grid preset when coming back on the page (like a user preference or coming back to the page with same filters and sorters), quite cool, you should take a look at it :) 

Also want to thank you again for the pagination page number input, I added it to my lib as well, which you can see [here](https://ghiscoding.github.io/Angular-Slickgrid/#/gridgraphql). So thank you :)

Note that I will merge your PR eventually, just been quite busy with this new feature.

**Comment by ghiscoding** [comment]
I worked with my coworker on his other project yesterday and he had an old version of Angular-Slickgrid (`0.8.0` I think he had) and at some point in time I changed the way to use `Angular-Slickgrid` in your App Module, it is now required to use it with the `forRoot()` else it will fail. Can you review the [HOWTO Step 4](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step#4-include-it-in-your-app-module). By the way, I had to bump latest to `0.12.1`, small issue with Pagination number.

Your errors are in French... tu parles Francais? moi aussi :P

**Comment by sabeurch** [comment]
C'est bien, merci :)
J'ai fait npm uninstall , puis npm install et c'est corrigé le problème.
Il parait que c'est un problème dans mon environnement (Je teste directement sur les souces et non pas depuis NPM, ceci me permet de modifier la source. J'utilise Eclipse comme IDE avec le plugin "Angular Eclipse 1.3.0"). 
Merci encore une autre fois !

**Comment by ghiscoding** [comment]
Je viens d'essayer le PR et c'est cool, j'aime bien le spinner et je n'avais pas penser à mettre une pagination dans le coin droit, c'est cool et différent. Et j'aime bien ton logger aussi, je risque de l'utiliser aussi pour notre projet. 

Merci encore, ça fera parti de la prochaine version. :)

**Comment by sabeurch** [comment]
Oui c'est un peu différent et c'est batu pour un besoin spécifique :)
Quant au logger, j'ai mis pour l'instant le niveau INFO en hardcodé:
 `private _clientLogLevel: LoggerLevel = LoggerLevel.INFO;`
Le mieux est de le paramétriser ou qu'il soit mis au niveau ERROR au moment de la génération du "dist".
Je serai ravi de suggérer plus de PRs dans les prochains jours.

**Comment by ghiscoding** [comment]
ah oui tu as quelques choses d'autres en tete? 
Par contre, il faudrait garder l'Anglais pour d'autre issue qui pourrait interesser les autres.

**Comment by sabeurch** [comment]
Yes, we dived into French.
Well, thinking especially about item editors: Those 2 facilities are in my planning, but milestone is not yet specified as other tasks in the work are taking my time:
1- Generic Formater, could be used to display different types of formatters in the same column. 
2- Column Header Formatter, you already introduced the use of Header Button Plugin and Header Menu, but it will be better for other purposes usage to use formatters rather than plugins. Example, if we want to add a checkbox into the column's header, developer will find it much easier.
Some other minors, like 
1- Using jsonpath library, it will be easier for developer to just set the basic URL+Json Xpath like expression for the datagrid. Datagrid will be self updating itself.
2- Also, image formatter based on based 64 encoded images. Images could be retrieved from DB& dynamically, no more need for assets folder. The idea comes from using "font awesome" or "glyphicon".

**Comment by ghiscoding** [comment]
J'ai ouvert un autre issue #18 pour les points que tu viens d'annoncer

**Comment by ghiscoding** [comment]
Ton [demo](https://ghiscoding.github.io/Angular-Slickgrid/#/swt) est maintenant live. Merci

**Comment by sabeurch** [comment]
Perfect merci!

**Pull request merged**
