### PR TITLE
fix(gridService): addItem/updatedItemById must pass an array to setSelectedRows

### PR DESCRIPTION
**Pull request by ljacques**
replace setSelectedRows to setSelectedRow

### CODE REVIEW

**Comment by ghiscoding** [comment]
Wow good catch, I never noticed the bug, `setSelectedRows` is the only method that SlickGrid (core) provides and yeah we always need to make sure to pass an array.

I think we need to modify some unit tests to make sure `setSelectedRows` is called with an array in both of the methods you fixed... Would you be able to modify the tests? or I can take a look if you want, just let me know. Thanks

**Comment by ljacques** [comment]
ok I will watch to change the tests as soon as I have some time ;-)

**Comment by ghiscoding** [comment]
I took a quick look at the test I have and I think I forgot to add a test for the selected row when using the singular `addItem` but I have a test for `addItems` with `setSelectedRows`. You can recopy the `addItems` plural test [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/__tests__/grid.service.spec.ts#L507)

Below is basically what is missing in the test (there is more code than that, it's just to show how it works).
```ts
const selectSpy = jest.spyOn(gridStub, 'setSelectedRows');
service.addItem(mockItem, { selectRow: true });
expect(selectSpy).toHaveBeenCalledWith([0]);
```

**Comment by ljacques** [comment]
I d'ont know why but my changes seem to affect a cypress test call
"should change "% Complete" filter range by using the slider left handle (min value) to make it a higher min value and expect all rows to be within new range" :(

**Comment by ljacques** [comment]
and now it's ok .... ^^

**Comment by ghiscoding** [comment]
I think that's the test that sometime fails (1/10) and re-running them works after.

**Comment by ljacques** [comment]
oups i'am using itellij and I mechanically apply automatic formatting.
wait i'am trying to rollback this.

**Comment by ghiscoding** [comment]
@ljacques 
C'est maintenant disponible sous la nouvelle version [2.12.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.12.0). Il y a une modification importante à faire pour le Prod Build, alors fait attention et lit au complet. 

Merci pour les contributions 😃

**Comment by ljacques** [comment]
héhé merci c'est ok j'ai récupéré la release  😃
j'ai repéré quelques soucis sur les filtres basé sur des composants angular, je vais travailler la dessus 👍

**Pull request merged**
