### PR TITLE
feat(OData): add `$select` and `$expand` query options

### PR DESCRIPTION
**Pull request by ghiscoding**
- follows original Slickgrid-Universal [PR #588](https://github.com/ghiscoding/slickgrid-universal/pull/588)

#### TODOs
- [x] requires newer Slickgrid-Universal version

### CODE REVIEW

**Comment by ghiscoding** [comment]
@jr01 
I created this PR to make sure your OData changes also work in Angular-Slickgrid and it seems that.. they don't actually work, I don't see the OData query update with the new `$select` and `$expand`, however it works just fine in Aurelia-Slickgrid.
Could you take a quick look at the PR and see if I missed anything?

I'm expecting to release new versions by the end of this week if I can finish all PRs, I think we still need the OData Wiki update as well, you can release couple days prior that shouldn't be a problem.

pMoUtpnVJa

**Comment by jr01** [comment]
> I think we still need the OData Wiki update as well, you can release couple days prior that shouldn't be a problem.

I will do that tomorrow!

**Comment by jr01** [comment]
@ghiscoding - I updated the OData wiki in both slickgrid-universal and angular-slickgrid repo's.  But I was thinking, instead of copy/pasting that content and making some mistake, wouldn't it be better to just remove the OData wiki page from angular-slickgrid repo and change the OData link in that wiki's index to point to the OData wiki in the universal repo? I guess it could be done for multiple wiki pages and I was wondering what your thoughts are on that?

**Comment by ghiscoding** [comment]
@jr01 
Thanks and to answer your question, that wouldn't work for every Wikis since some of them have Angular/Aurelia or plain TS specific code, so I kinda have to keep them separate for that reason. For example, whenever I show `<angular-slickgrid>...`

**Comment by ghiscoding** [comment]
Now released with [version 4.1.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v4.1.0)

Thanks for another great contribution 😄

**Pull request merged**
