### PR TITLE
fix(core): unsubscribe every possible events

### LINKED ISSUE #610: Angular-Slickgrid is causing a memory leak in my application
### Your Environment
| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 10.1.6        | 
| Angular-Slickgrid   | 2.22.4        | 
| TypeScript              | 4.0.3       | 

### Describe the Bug
It's been a couple of days that I'm trying to figure out why certain aspects of my angular application are slow. After much hassle I finally figure out that my destroyed components are not getting unloaded from memory. I use the memory tab in chrome tools, I take a snapshot of the heap and all my components are times the amount of time I switched between views, which is a big problem because this slows down the application a lot.
So I decided I'm going to take out most of the code and just have the skeleton of the components and have the ability to route between them and I kept removing code until the problem was gone. It turns out that as long as I don't add angular slick grid to my html component I'm fine. As soon as I add it, this problem happens.
It usually means that you might have even listeners that are still open, or something like that, that's preventing the GC to unload them from memory.
As a matter of fact I downloaded the Angular-Slickgrid project and ran the examples locally, and than ran the same memory test. And sure enough same problem the components keep piling up as I switch between them.

image

The strange thing is that if I compile Angular-Slickgrid in prod mode, I don't see any components in the heap (meaning to say I don't see any objects that end with the word component) nor do I see any objects that resemble the components in examples, why is that? The only thing I can find is SlickGrid and every click adds another instance in prod build as well.

If you can shed some light into this would be very much appreciated, I'm at loss what to do next.

### Steps to Reproduce
as mentioned above just run the examples, keep toggling between components a couple of times. Then hit F12 to bring up Chrome Dev Tools, go to the memory tab, in the Heap snapshot option there's a Take snapshot button, hit that. Once the snapshot is loaded, you can filter by component, and you'll see that 

### Expected Behavior
Destroyed components should be garbage collected and should not persist in memory.

### Current Behavior
Components are not being removed from the heap.

### Code Sample
The Angular-Slickgrid sample shows this problem

### PR DESCRIPTION
**Pull request by ghiscoding**
- causes memory heap size to keep growing
- ref #610

### CODE REVIEW

**Comment by ghiscoding** [comment]
@tannenbaums
I made some more changes, I found all the ngx-translate subscriptions weren't unsubscribe and I reverted all the Subject `.complete` because we should technically only unsubscribe a subscriptions. 

There is only 1 more subscription that I'm not sure how to unsubscribe since it's in the App Module (appInitializerFactory) on this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/app.module.ts#L70). I'm not sure if it's even possible but that is a possible left open one. 

So give that another try and see if latest commits help. Thanks

**Comment by tannenbaums** [comment]
Sounds great, I’ll check it out a bit later, I have to juggle my work load with this. I made my own changes, but didn’t get a chance to test yet. But I’ll try your first when I get freed up…

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by tannenbaums** [comment]
Definitely making progress, the BasicGridComponent is not leaking anymore but the others still do. I’ll continue to try fixing on my end and look into that line in app module.

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by tannenbaums** [comment]
I’d like to mention another point: if you assign the subscription to a variable like this:

        this.changeSubscriber = componentOuput.componentRef.instance.onItemChanged.subscribe((item) => {

and then unsubscribe on destroy, there can still be a problem. Because if the method that subscribes get called more than once, what happens is, your variable only has a ref to the last subscription, but the other ones from previous calls are still floating around. So I think that it’s safer to always add them to a collection like yours subscriptions collection. Because then when we loop over the collection and unsubscribe it’ll get every single one of them.

In the version that I started modifying (but didn’t have a chance to finish yet, because had to deal with users) I added another field to the SharedService called OpenedSubscriptions and added the service to every component that needed this treatment, and then pushed every subscription that was floating onto it. And then in angular-slickgrid component.destroy I just added this line

    this.sharedService.globalSubscriptions = unsubscribeAllObservables(this.sharedService.openSubscriptions);

right below this:

    // also unsubscribe all RxJS subscriptions
    this.subscriptions = unsubscribeAllObservables(this.subscriptions);

What do you think?

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260


From: Shmuel Tannenbaum
Sent: Monday, October 26, 2020 3:59 PM
To: ghiscoding/Angular-Slickgrid <reply@reply.github.com>; ghiscoding/Angular-Slickgrid <Angular-Slickgrid@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ghiscoding/Angular-Slickgrid] fix(core): every Subject should be destroyed, fixes #610 (#611)

Definitely making progress, the BasicGridComponent is not leaking anymore but the others still do. I’ll continue to try fixing on my end and look into that line in app module.

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
Sure I can change them to loop through subscriptions array, I'll do that tomorrow but I doubt that would make much difference in this case though.

**Comment by ghiscoding** [comment]
@tannenbaums
I made the changes you asked, but since you said the 1st Example (basic grids) is no longer showing the issue, I wonder if it could be the Resizer Service causing the issue (it has a body resize binding event which is unbind on destroy). So maybe if you could try toggling between these Examples (1, 6, 10, 15, 20) that don't have the auto-resize enabled and see if those grids are having the leak or not. Thanks

**Comment by tannenbaums** [comment]
Looks like one more example is good now: 10 RowSelection.

The others are still the same problem.

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
Well I can't go further than that, so if you find something else than please share it, else I will merge the PR as it is in the coming days.

**Comment by tannenbaums** [comment]
Ok np. I will continue to try things out on my end though.

Thank you for all your help!!

[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
Sure I would of course rather fix any memory leaks as much as possible. When you said only Example 10 got fixed, are the other grids without auto-resize still leaking (Examples 1, 6, 10, 15, 20)? I think you have only confirmed Examples 1 and 10 so far, not sure about the others. I also only rewrote the Example 4 to use an `ngOnDestroy` and call Angular-Slickgrid destroy, I don't think that would be ideal anyway (technically we shouldn't have to call destroy ourselves I would think).

**Comment by tannenbaums** [comment]
Sorry I wasn’t clear, I was confirm that 1 and 10 got fixed and all the others you mentioned: 6, 15, 20 are still leaking.
Yes I think so too, Angular called destroy for you.

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
@tannenbaums 
I found 2 other possible leaks (most probably have a big effect)
1. an event that was bound to `document` (onKeyDown) that was inside the ExternalCopyManager plugin which was enabled in about 10 examples. 
2. inside the `multiple-select.js` 3rd party lib that I customized to use with Single/MultipleSelect Filters/Editors, I added an `onClick` on the `body` so that clicking anywhere on the body would close the dropdown but it I forgot to unbound it when I did that code change some time ago.

The fact that that both were bound to document/body were most probably a big memory leak, especially number 2 I would assume since it's used in most grids. 
You can give another try, that should help a bit

**Comment by tannenbaums** [comment]
I ran a test on your latest changes, and I tested 1 to 20.
The results:

Pass:
1,4,8,10,14,16,18

Fail:
2,3,5,6,7,9,11,12,13,15,17,19,20

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
Well I am done on my side, there's nothing else for me to search for, I have fixed everything I could find. 

What you could do to help though is go on these Examples and disable all the grid option flags to disable most extensions/plugins and see if it stops leaking then re-enable some of these flags to find what extension/plugin might be leaking. You can start by disabling `enableExcelCopyBuffer` and `enableAutoResize`.

**Comment by tannenbaums** [comment]
Yes exactly!
So I finally found what makes the 2nd example leak.  It’s this code:

      {
        id: 'completed', name: 'Completed', field: 'completed', type: FieldType.number, sortable: true, minWidth: 100,
        formatter: customEnableButtonFormatter,
        onCellClick: (e, args) => {
          this.toggleCompletedProperty(args && args.dataContext);
        }
      }

If you remove the line in italic, it’ll stop leaking. I think the reason is because this basically causes that the grid now has a ref to a column object which has an onCellClick event that has a ref to a method in the component (in this case the Formatter component), so it won’t release the component. But I’m not sure how to fix it. What do you think?

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by tannenbaums** [comment]
Right now my only way to resolve this is declare the method outside the component, which works, but I hope there’s a better solution…

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260


From: Shmuel Tannenbaum
Sent: Wednesday, October 28, 2020 3:51 PM
To: ghiscoding/Angular-Slickgrid <reply@reply.github.com>; ghiscoding/Angular-Slickgrid <Angular-Slickgrid@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ghiscoding/Angular-Slickgrid] fix(core): every Subject should be destroyed, fixes #610 (#611)

Yes exactly!
So I finally found what makes the 2nd example leak.  It’s this code:

      {
        id: 'completed', name: 'Completed', field: 'completed', type: FieldType.number, sortable: true, minWidth: 100,
        formatter: customEnableButtonFormatter,
        onCellClick: (e, args) => {
          this.toggleCompletedProperty(args && args.dataContext);
        }
      }

If you remove the line in italic, it’ll stop leaking. I think the reason is because this basically causes that the grid now has a ref to a column object which has an onCellClick event that has a ref to a method in the component (in this case the Formatter component), so it won’t release the component. But I’m not sure how to fix it. What do you think?

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
hmm that is that, under the hood the column `onCellClick` is a connected to the SlickGrid `onClick` event, I'm using the SlickGrid Event Handler to subscribe ([here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/gridEvent.service.ts#L46)) and unsubscribeAll ([here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/services/gridEvent.service.ts#L78)) and if I look at the Angular-Slickgrid component, I am disposing (destroying) of that GridEvent Service properly on this [line](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/components/angular-slickgrid.component.ts#L276)) and everything looks fine from my point of view, that is strange.

So as I wrote in first paragraph, technically speaking the `onCellClick` is a connected to the SlickGrid `onClick` event.
Could you try to take 1 of them that leaks and replace the column `onCellClick` with the regular SlickGrid event and move the code into a separate method `onCellClicked` like so:
```html
<angular-slickgrid gridId="grid22" (onAngularGridCreated)="angularGridReady($event)"
                       (sgOnClick)="onCellClicked($event.detail.eventData, $event.detail.args)"
                       [columnDefinitions]="columnDefinitions" [gridOptions]="gridOptions" [dataset]="dataset">
    </angular-slickgrid>
```

I'd like to know if it's really that GridEventService causing the issue

> If you remove the line in italic, it’ll stop leaking.
> Right now my only way to resolve this is declare the method outside the component, which works, but I hope there’s a better solution…

BTW, I don't see any italic line in your GitHub reply, maybe because you replied by email, so I'm not fully sure what you mean in this quote, would you mind pasting the code change you did.

**Comment by ghiscoding** [comment]
The `toggleCompletedProperty` method has a `setTimeout`, I wonder if that causes problem

**Comment by tannenbaums** [comment]
No. Even if you comment out the body of the toggleCompletedProperty method it’s still a problem.

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
Can you try what I wrote in this [previous comment](https://github.com/ghiscoding/Angular-Slickgrid/pull/611#issuecomment-718226817) then

**Comment by tannenbaums** [comment]
So sorry, it’s this line:

this.toggleCompletedProperty(args && args.dataContext);

Still working on it…

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by tannenbaums** [comment]
Yes! No leak when I do that.

Can I ask you: at this point you put a lot of wonderful fixes in your lib. Would you be able to make an official release, so that I can test it in my application? Is there a way for me to do it without a release from you? I’m not so familiar with this part, never published a library…

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
I would rather wait to fix this bug first as much as we could, in the mean time what you can do is to run this npm script `yarn run build` (if you use VSCode, you can run the task named "Build Library") that will delete and recreate the `dist` folder then once that is done you can simply copy the entire content of it and go to your folder `node_modules/angular-slickgrid` delete the content and paste the new code from `dist`. You don't need to publish anything on npm, I often use that technique to test some code without publishing a new version (that works with any npm library as well)

in the mean time let me merge master into the branch since there are couple of other fixes that went through

**Comment by tannenbaums** [comment]
Ok I’ll try that, thank you!

Regarding the bug: I think (and this is just my two cents) that, this one is not a subscribe/unsubscribe issue, but rather that some code either in Angular-Slickgrid or maybe in SlickGrid itself, is not clearing out the reference to the column definition collection. And thus, in this case, the collection contains an even handler that has a ref to the GridFormatterComponent (because the even handler contains this.toggleCompletedProperty(), and “this” is pointing to the component). And that’s why it’s not being released from memory. That’s why, if I move the toggleCompletedProperty method outside of the component (I declare a const on top of the component) the problem goes away.

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by tannenbaums** [comment]
I’ve never used yarn before. After installing and running yarn run build on the root of the project (which includes the samples) I get all these errors (attached). Any idea?

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
I can't see your attachment, probably because you replied by email, you should use GitHub website to add print screen, you can run `npm run build` if you don't use Yarn.

I'd like to confirm if you tried with the regular SlickGrid `onClick` method via the html, does that leak too? If it does then there's something wrong with the GridEventService and I'd like to confirm that.

```html
<angular-slickgrid gridId="grid22" (onAngularGridCreated)="angularGridReady($event)"
                       (sgOnClick)="onCellClicked($event.detail.eventData, $event.detail.args)"
                       [columnDefinitions]="columnDefinitions" [gridOptions]="gridOptions" [dataset]="dataset">
</angular-slickgrid>
```

**Comment by tannenbaums** [comment]
Yes sorry I was using email.
Yes I did your suggestion of putting it in the html exactly as you suggested below, and then there’s NO leak!!

I tried running npm run build, but it’s just returning gracefully and nothing seems to be happening.

Can I put the errors directly here in the email? It’s a bunch of these:

BUILD ERROR
node_modules/@types/babel__traverse/index.d.ts(212,49): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(212,53): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(212,55): error TS1005: ';' expected.
node_modules/@types/babel__traverse/index.d.ts(212,57): error TS1109: Expression expected.
node_modules/@types/babel__traverse/index.d.ts(212,61): error TS1005: ';' expected.
node_modules/@types/babel__traverse/index.d.ts(212,69): error TS1128: Declaration or statement expected.
node_modules/@types/babel__traverse/index.d.ts(212,83): error TS1011: An element access expression should take an argument.
node_modules/@types/babel__traverse/index.d.ts(213,9): error TS1136: Property assignment expected.
node_modules/@types/babel__traverse/index.d.ts(213,31): error TS1005: ']' expected.
node_modules/@types/babel__traverse/index.d.ts(213,32): error TS1005: ';' expected.
node_modules/@types/babel__traverse/index.d.ts(213,33): error TS1128: Declaration or statement expected.
node_modules/@types/babel__traverse/index.d.ts(213,65): error TS1005: '(' expected.
node_modules/@types/babel__traverse/index.d.ts(214,5): error TS1135: Argument expression expected.
node_modules/@types/babel__traverse/index.d.ts(214,9): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(215,19): error TS1005: '(' expected.
node_modules/@types/babel__traverse/index.d.ts(216,12): error TS1005: ')' expected.
node_modules/@types/babel__traverse/index.d.ts(347,48): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(347,52): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(347,54): error TS1005: ';' expected.
node_modules/@types/babel__traverse/index.d.ts(347,61): error TS1005: ')' expected.
node_modules/@types/babel__traverse/index.d.ts(347,68): error TS1005: ';' expected.
node_modules/@types/babel__traverse/index.d.ts(347,69): error TS1128: Declaration or statement expected.
node_modules/@types/babel__traverse/index.d.ts(347,87): error TS1005: '(' expected.
node_modules/@types/babel__traverse/index.d.ts(356,40): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(356,46): error TS1005: ';' expected.
node_modules/@types/babel__traverse/index.d.ts(359,31): error TS1005: '?' expected.
node_modules/@types/babel__traverse/index.d.ts(359,44): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(359,61): error TS1005: '(' expected.
node_modules/@types/babel__traverse/index.d.ts(359,62): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(359,76): error TS1005: '(' expected.
node_modules/@types/babel__traverse/index.d.ts(359,77): error TS1005: ')' expected.
node_modules/@types/babel__traverse/index.d.ts(366,60): error TS1005: '?' expected.
node_modules/@types/babel__traverse/index.d.ts(366,66): error TS1005: ':' expected.
node_modules/@types/babel__traverse/index.d.ts(366,73): error TS1005: ',' expected.
node_modules/@types/babel__traverse/index.d.ts(366,81): error TS1005: ';' expected.
node_modules/@types/babel__traverse/index.d.ts(366,99): error TS1005: '(' expected.

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
ahh yeah I remember that problem, I had it too, I think it's because I need a newer version of TypeScript in the project because, for some unknown reasons it updated to latest version of `@types/babel__traverse` which is an indirect dependency so I don't have any control to downgrade it. I had to take an older version of `@type/babel` and overwrite the one I have in Angular-Slickgrid... 

long story short, it's probably easier if I release a version tomorrow

**Comment by tannenbaums** [comment]
I’m glad you came to that conclusion…☺

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
I found out that if we overwrite the `index.d.ts` file of `Angular-Slickgrid\node_modules\@types\babel__traverse` with the attached `index.d.ts` file (an older version) it finally compiles. From what I found by reading this SO [question](https://stackoverflow.com/questions/63903376/angular-node-modules-types-babel-traverse-index-d-ts1137-43-error-ts1109), newer TypeScript changed the output of `index.d.ts` and my lib uses an older TypeScript version because the lib project is still under Angular 7.

[babel__traverse.zip](https://github.com/ghiscoding/Angular-Slickgrid/files/5455589/babel__traverse.zip)

**Comment by ghiscoding** [comment]
I pushed a new patch version `"angular-slickgrid": "^2.22.5"`, now I just need to spend a few minutes to update all the Angular-Slickgrid-Demos with the changes done in the Examples. You should be good to go, I'm not sure what to do with the GridEventService that has the column `onCellClick`, you said it doesn't leak when using the event inside the View (html), I could always deprecate it in the next major version but I find it useful to declare it right in the column definitions... anyway, if it fixes all your leak then that's a big push in the right direction

**Comment by tannenbaums** [comment]
Thank you for that! I’m not sure, I updated to the latest but still not seeing results. Let me ask you this:
I see that there’s 2.22.5 and ^2.22.5 do I need to make sure I get the one with ^? Or do they both have the mem-leak fixes?

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
I pushed the changes under latest version `2.22.5`, if you use the carrent `^` then it will update all minor (the 2nd number `22`), if you use `~` it will update the last number `5`

**Comment by tannenbaums** [comment]
Oh I see, ok.

Well sadly to say, I have an empty component, even if I add just add this: (with nothing in the ts file)

<angular-slickgrid

                           >
        </angular-slickgrid>

I have a leak, and if I remove: no leak. This is crazy.

Do you think it might have to do with the fact that I’m using the latest version of angular, while angular-slickgrid is using 7?

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
I don't think that the version of Angular I use has anything to do with that, to create the lib package I use [ng-packagr](https://github.com/ng-packagr/ng-packagr), that produces UMD and other file types. If there's anything, it should be `ng-packgr` not really Angular itself. However I made a PR last night for Angular 8 in the project with also a bit newer version of `ng-packagr` (it was mainly to fix the ton of errors message with `@types/babe__traverse` that you saw yesterday)... so you can try that PR #617 and run the `yarn run build` and copy the `dist` folder content and overwrite your `node_modules/angular-slickgrid` folder and see if that helps. 

I'm not sure that I want to go over Angular 8 in the lib project yet, I know they changed to Ivy in Angular 9 so I wanted to stick with Angular 8 for some time. The PR #617 for Angular 8 is not merged yet, I'll do a future release as a `minor` (so that would `2.23.0`) but I'm not in a rush, unless you tell me it helps (which I doubt). If that doesn't fix it and you have some time, you can try upgrading the lib project to Angular 10 and if that does fix the leaking then I'll go for it.

**Comment by tannenbaums** [comment]
I hear you. In the meantime I decided to start digging in the heap and see if I can trace where does Angular-Slickgrid hold a ref to my component, which in this specific case it’s called: CaseListingComponent
Check out below, looks like ViewRef inside AngularSlickgridComponent is holding a ref to CaseListing…

[cid:image001.png@01D6AE06.547E79E0]

Thank you,
[Logo2]

Shmuel Tannenbaum
1776 Avenue of the States, Suite 103
Lakewood, New Jersey 08701
Phone: 732-645-9800 ext:260

**Comment by ghiscoding** [comment]
Every time you post a print screen of attachment via an email reply I can't see it in GitHub, so I don't know what you posted. If you have a way to fix whatever you posted, please make a PR, there isn't much more I can do on my side. Thanks

**Comment by tannenbaums** [comment]
So sorry I keep forgetting, ok now I'm replying on the post. I didn't realize it moved to a different thread than the one I started that's what got me confused...

image

**Comment by ghiscoding** [comment]
Ok I now see the image but it's too small, I can't see the text lol... but still I don't know what else to do. What are the grid options that you're using with that grid? I assume you use some of the features.

**Comment by tannenbaums** [comment]
Here's a better image, it's really important, it shows where the leak is:

image

**Comment by ghiscoding** [comment]
That is a great reference but I still don't have a clue on how to fix that, I don't know Angular in depth enough (I understand the ViewRef concept but I don't understand what is good and what is wrong) so I don't know what to know (in fact I haven't used Angular in couple months, we are using something else for current project). If you have a way to fix it, please please make a PR.

**Comment by tannenbaums** [comment]
Well in AngularUtilService you are assigning a viewRef I thought it has todo with that...no?

**Comment by tannenbaums** [comment]
you have a line like this:

this.appRef.attachView(componentRef.hostView);

this looks like it has a lot to do with this issue...but i might be wrong...
maybe there's a way to release it when component is destroyed...

**Comment by ghiscoding** [comment]
So you're using the Row Detail then, if you see in the AngularUtilService, there's a link which point to what I found to dynamically load an Angular Component into the Row Detail. The link is [Angular Pro Tip: How to dynamically create components in <body>](https://hackernoon.com/angular-pro-tip-how-to-dynamically-create-components-in-body-ba200cc289e6). I did not analyze the code much, I just reuse what was in the article to get the Row Detail working (AngularUtilService is mainly used for Row Detail only).

**Comment by tannenbaums** [comment]
All I have is an html template which contains:
  `<angular-slickgrid> </angular-slickgrid>`
that's it!! no other code (the ts file is just an empty constructor)!! and that's causing the image that I sent.

**Comment by ghiscoding** [comment]
Well I don't know why because as I said that ViewRef that you found is really only used by the Row Detail (I search in the lib), so I don't know why it creates that structure.

**Comment by tannenbaums** [comment]
I have very good news!!! I didn't test it properly this morning, must have been some sort of a refresh/caching issue.
I retested and NO MORE LEAK!!!! now that's exciting news!!!!!

Thank you so much for all your on-going help and support!!

**Comment by ghiscoding** [comment]
that is indeed excellent news, thanks for all the communication and feedback 🚀 😄

**Comment by tannenbaums** [comment]
Hi,

I just opened up another issue. Although this type of memory leak is fixed, I found another memory leak called DOM Leak which is even a bigger issue. And it's probably the cause for the issue I'm having in my application. I'm working on this for just about 2 weeks. If you can take a look I would greatly appreciate.

**Pull request merged**
