### PR TITLE
fix(styling) compilation bug due to missing calc in variables.scss

### PR DESCRIPTION
**Pull request by fheck**
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 8.2.3        | 
| Angular-Slickgrid   | 2.19.0        | 
| TypeScript              | 3.9.6        | 

### Describe the Bug
When using a $font-size-base value set to rem, an error occurred during compilation stating "Incompatible units px and rem".

### Steps to Reproduce
In styles.scss, before importing the variables.scss, set $font-size-base to 1rem.

### Expected Behavior
It compiles.

### Current Behavior
It does not compile, with the error mentioned above.

### Possible Solution
Add missing calc in lines 276 and 315 as seen in this PR.

### Code Sample
Not needed.

### CODE REVIEW

**Comment by ghiscoding** [comment]
@fheck 
Good catch, however I see a few more missing the `calc`, could you please add it to every other variable, I counted 12 to change in total, you can see this [commit](https://github.com/ghiscoding/slickgrid-universal/commit/054a9b05cb08fe1fcab918e5faf316ce3110c72e) to apply your patch in my other lib `Slickgrid-Universal`

**Comment by fheck** [comment]
I added all I could find, with a total of 12 it matches yours. Initially I only fixed those two, because that were the only ones that prevented compilation for me and I didn't look beyond.

**Comment by ghiscoding** [comment]
Thanks for that, I'll release a new version in a week or 2 so hopefully you can wait a bit more

**Comment by fheck** [comment]
Yeah, I've rolled back the upgrade for now because the actual problem I was looking into is somewhere with Slickgrid itself and the update did not fix it yet. So I need to look into it some more anyways.

**Comment by ghiscoding** [comment]
what kind of problem and/or upgrade have you done? do you mean some issues in your code or the lib?

**Comment by fheck** [comment]
I believe it is in the slickgrid lib. I can't tell tell the exact problem yet, but when having frozen columns, searchable columns and autoHeight enabled, slickgrid calculates the height of the viewport too small by the height of the header row (the one with the search boxes). Currently I do not have a minimal example because we have an additional wrapper layer on top of the your module (for embedding with an existing data source). 
I had hoped your PRs in the slickgrid code would help but even with the current version the problem persists. I will look into it some more..

**Comment by ghiscoding** [comment]
I personally never use the `autoHeight` flag as I prefer to only have auto-resizable grid or fixed sizes, but the last time we touched the `autoHeight` in the SlickGrid core lib was this [issue](https://github.com/6pac/SlickGrid/pull/342) which was also reported in this Angular-Slickgrid [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/143)... not sure if that has anything to do with your issue but you might want to read and/or try some changes in the core lib. I know there was an issue once in the core and we introduced a bug while trying to fix something, we ended up having to revert it since it introduced a bug (anyway you can read the full story in the issues I referenced).

**Comment by ghiscoding** [comment]
@fheck 
This PR is actually causing me some problems in my other lib, SASS doesn't like to calc with SASS variables and it has to be escaped before trying to use a SASS variables. As answered in this [SO - Answer](https://stackoverflow.com/a/20236515/1212166)

Basically this
`calc(17px * $header-row-count)`
should be changed to this (notice the `#{sass-var}`
`calc(17px * #{$header-row-count})`

I'd be happy to confirm that this also works on your side.

**Comment by fheck** [comment]
Can confirm, that works for me as well. Sorry I missed that.

**Comment by ghiscoding** [comment]
no worries and thanks for the confirmation, I've pushed a new version `2.19.1` including this PR. 
Thanks for the contribution.

**Comment by ghiscoding** [comment]
@fheck 
This is now available in the new release [2.20.1](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.20.1)

Cheers ⭐

**Pull request merged**
